# testing for signup
POST http://localhost:80/authCustom HTTP/1.1
content-type: application/json


{
    "Name": "Archit",
    "Email": "example@example123.com",
    "Password": "Hello world",
    "location":[{
        "AcceptedEmail": "example@example.com",
        "AcceptedName": "asdfasd",
        "lat": 100,
        "long": 100
    }]
}

###

# testing for logging in
POST http://localhost:80/authlogin HTTP/1.1
content-type: application/json


{
    "Email": "example@example123.com",
    "Password": "Hello world"
}