const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const authSchema = new Schema({
  // id is generated by mongodb
  Name: {
    type: String,
    required: true,
  },
  Email: {
    type: String,
    required: true,
  },
  Password: {
    type: String,
    required: true,
  },
  // PhotoUrl: {
  //   type: String,
  //   required: true,
  // },
  location: [
    {
      AcceptedEmail: String,
      AcceptedName: String,
      // AcceptedPhotoUrl: String,
      lat: mongoose.Types.Decimal128,
      long: mongoose.Types.Decimal128,
    },
  ],
});
const AuthModel = mongoose.model("authModel", authSchema);

module.exports = AuthModel;
